### ISSUE TITLE
50% chance

### ISSUE THREAD

**Issue by iamraf** [esentis/OOP-IHU-Exams-6-7-2020#1]
https://github.com/esentis/OOP-IHU-Exams-6-7-2020/blob/376a74da85d67f38f5e5dae8183582a3c78317d8/K2_Thema3/src/k2/TestSalary.java#L73

Unfortunately, this is not going to produce 50% chance of being 0 of 1. It will generate a random number which will happen to be 0 or 1, but not in a 50% chance.

You can simply achieve this by using module to check if variable **_i_** is even or odd number which will produce the same amount of the 2 objects inside the array.

I have made a simple test which you can check and run [here](https://onlinegdb.com/SygUHi5NkD).

Nice solutions, good job.

**Comment by akritikos** [comment]
The second method does not provide randomness, it is simply an alternating series of 0s and 1s and fully deterministic at that.
When randomness is requested, the outcome isn't judged by whether all outcomes appear in the same amount, but on whether they were generated fairly with equal probability.

Math.random provides enough entropy to guarantee that, unless the generated numbers are used in cryptography, in which case, java.security.SecureRandom would have been the obvious choice

cf: https://math.stackexchange.com/questions/12348/probability-of-getting-50-heads-from-tossing-a-coin-100-times

I still would have gone with this, for simplicity:
```java
Math.random() > 0.5 ? 0: 1;
```

**Comment by iamraf** [comment]
@akritikos seems i payed more attention at achieving 50% chance rather than focusing on the random part. Nice catch.
